coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flags:
  unit:
    paths:
      - src/
    carryforward: true
  e2e:
    paths:
      - src/
    carryforward: true

comment:
  require_changes: true
