import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import importX from 'eslint-plugin-import-x';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier/flat';

export default tseslint.config(
  // Generated output: build artefacts, coverage and Playwright reports, the locale
  // bundles emitted from scripts/data/*.yaml, and MSW's worker (vendored verbatim by
  // `msw init` — linting it would only ever report on someone else's code).
  {
    ignores: [
      'dist',
      'coverage',
      'playwright-report',
      'test-results',
      'src/i18n/locales/**',
      'public/mockServiceWorker.js',
      // Generated by the TanStack Router plugin — committed, but not ours to lint.
      'src/routeTree.gen.ts',
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'import-x': importX,
      'jsx-a11y': jsxA11y,
    },
    settings: {
      // Teaches the import rules to follow the `~/*` alias from tsconfig.
      'import-x/resolver-next': [
        createTypeScriptImportResolver({
          project: ['./tsconfig.app.json', './tsconfig.node.json'],
        }),
      ],
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // Type-only imports are erased at build time; marking them explicitly keeps
      // `verbatimModuleSyntax` honest and avoids accidental runtime imports.
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'separate-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // One import order, enforced rather than described: node/external first, then
      // internal `~/...`, then relative — each group separated by a blank line.
      // `type` is deliberately absent from `groups`: a type import sorts next to the
      // module it comes from, rather than being exiled to a block of its own.
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          pathGroups: [{ pattern: '~/**', group: 'internal', position: 'before' }],
          'newlines-between': 'always',
          distinctGroup: false,
        },
      ],
      'import-x/no-duplicates': 'error',
      'import-x/no-self-import': 'error',
      'import-x/no-cycle': ['error', { maxDepth: 4 }],
    },
  },

  /**
   * Architectural boundaries, enforced mechanically.
   *
   * `config/` holds plain values, `lib/` holds configured clients, `utils/` holds
   * pure helpers. The dependency arrow only ever points one way — features may use
   * all three, but none of the three may reach back into features. A rule catches
   * this on every commit; a paragraph in a doc does not.
   *
   * Deep cross-feature imports are deliberately NOT restricted yet: today the
   * `features/*​/index.tsx` files are react-router route modules, not public-API
   * barrels, so there is no boundary to point the rule at. That rule lands together
   * with the routing migration and the per-feature public surface, against a
   * structure that can actually satisfy it.
   */
  {
    files: ['src/utils/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['~/lib/*', '~/features/*', '~/stores/*', '~/components/*'],
              message:
                'utils/ must stay pure helpers: no clients (lib/), features, stores, or components.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/config/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['~/lib/*', '~/features/*', '~/components/*', '~/stores/*'],
              message:
                'config/ holds values only — it must not depend on clients, features or stateful stores.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/lib/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['~/features/*'],
              message: 'lib/ holds configured clients — features depend on it, never the reverse.',
            },
          ],
        },
      ],
    },
  },

  // Config, scripts and e2e run in Node, not the browser.
  {
    files: ['*.config.{js,ts}', 'scripts/**/*.ts', 'e2e/**/*.ts'],
    languageOptions: { globals: globals.node },
  },

  /**
   * Test infrastructure is not shipped, so the rules that protect the bundle and Fast
   * Refresh do not apply. `render.tsx` deliberately re-exports Testing Library's
   * surface so a test file has one import — react-refresh cannot see through
   * `export *`, and there is no HMR boundary here to protect.
   */
  {
    files: ['src/testing/**/*.{ts,tsx}'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },

  eslintConfigPrettier
);
