/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppTicketsIndexRouteImport } from './routes/_app/tickets/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminTeamsRouteImport } from './routes/_app/admin/teams'
import { Route as AppAdminTagsRouteImport } from './routes/_app/admin/tags'
import { Route as AppAdminSlaPoliciesRouteImport } from './routes/_app/admin/sla-policies'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppAdminPermissionsRouteImport } from './routes/_app/admin/permissions'
import { Route as AppAdminCategoriesRouteImport } from './routes/_app/admin/categories'
import { Route as AppAdminCannedResponsesRouteImport } from './routes/_app/admin/canned-responses'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminTeamsRoute = AppAdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminTagsRoute = AppAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminSlaPoliciesRoute = AppAdminSlaPoliciesRouteImport.update({
  id: '/sla-policies',
  path: '/sla-policies',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminPermissionsRoute = AppAdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminCategoriesRoute = AppAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminCannedResponsesRoute = AppAdminCannedResponsesRouteImport.update({
  id: '/canned-responses',
  path: '/canned-responses',
  getParentRoute: () => AppAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/admin/canned-responses': typeof AppAdminCannedResponsesRoute
  '/admin/categories': typeof AppAdminCategoriesRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/sla-policies': typeof AppAdminSlaPoliciesRoute
  '/admin/tags': typeof AppAdminTagsRoute
  '/admin/teams': typeof AppAdminTeamsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/': typeof AppAdminIndexRoute
  '/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/admin/canned-responses': typeof AppAdminCannedResponsesRoute
  '/admin/categories': typeof AppAdminCategoriesRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/sla-policies': typeof AppAdminSlaPoliciesRoute
  '/admin/tags': typeof AppAdminTagsRoute
  '/admin/teams': typeof AppAdminTeamsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin': typeof AppAdminIndexRoute
  '/tickets': typeof AppTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/canned-responses': typeof AppAdminCannedResponsesRoute
  '/_app/admin/categories': typeof AppAdminCategoriesRoute
  '/_app/admin/permissions': typeof AppAdminPermissionsRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/sla-policies': typeof AppAdminSlaPoliciesRoute
  '/_app/admin/tags': typeof AppAdminTagsRoute
  '/_app/admin/teams': typeof AppAdminTeamsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/canned-responses'
    | '/admin/categories'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/sla-policies'
    | '/admin/tags'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/admin/canned-responses'
    | '/admin/categories'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/sla-policies'
    | '/admin/tags'
    | '/admin/teams'
    | '/admin/users'
    | '/admin'
    | '/tickets'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/'
    | '/_app/admin/canned-responses'
    | '/_app/admin/categories'
    | '/_app/admin/permissions'
    | '/_app/admin/roles'
    | '/_app/admin/sla-policies'
    | '/_app/admin/tags'
    | '/_app/admin/teams'
    | '/_app/admin/users'
    | '/_app/admin/'
    | '/_app/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tickets/': {
      id: '/_app/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/teams': {
      id: '/_app/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AppAdminTeamsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/tags': {
      id: '/_app/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AppAdminTagsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/sla-policies': {
      id: '/_app/admin/sla-policies'
      path: '/sla-policies'
      fullPath: '/admin/sla-policies'
      preLoaderRoute: typeof AppAdminSlaPoliciesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/permissions': {
      id: '/_app/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AppAdminPermissionsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/categories': {
      id: '/_app/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AppAdminCategoriesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/canned-responses': {
      id: '/_app/admin/canned-responses'
      path: '/canned-responses'
      fullPath: '/admin/canned-responses'
      preLoaderRoute: typeof AppAdminCannedResponsesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminCannedResponsesRoute: typeof AppAdminCannedResponsesRoute
  AppAdminCategoriesRoute: typeof AppAdminCategoriesRoute
  AppAdminPermissionsRoute: typeof AppAdminPermissionsRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSlaPoliciesRoute: typeof AppAdminSlaPoliciesRoute
  AppAdminTagsRoute: typeof AppAdminTagsRoute
  AppAdminTeamsRoute: typeof AppAdminTeamsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminCannedResponsesRoute: AppAdminCannedResponsesRoute,
  AppAdminCategoriesRoute: AppAdminCategoriesRoute,
  AppAdminPermissionsRoute: AppAdminPermissionsRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSlaPoliciesRoute: AppAdminSlaPoliciesRoute,
  AppAdminTagsRoute: AppAdminTagsRoute,
  AppAdminTeamsRoute: AppAdminTeamsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
