import { setupWorker } from 'msw/browser';

import { handlers } from '~/mocks/handlers';

/**
 * MSW in the browser — the mock API behind the static demo build, and the reason
 * the app can run with no backend at all.
 *
 * Requires `public/mockServiceWorker.js`, generated by `bunx msw init public/`.
 * The file is committed rather than generated at build time: Vite copies `public/`
 * verbatim, and a worker that only exists on the machine that ran `init` produces
 * a demo that works locally and 404s in production.
 */
export const worker = setupWorker(...handlers);
